import type { Response } from 'express';
import PDFDocument from 'pdfkit';
import { ApiResponse, buildError, buildSuccess } from '../../../utils/response';
import { toErrorResponse } from '../../../utils/errorHandler';
import { buildListResponse } from '../../../utils/pagination';
import { BuiltQuery } from '../../../utils/queryBuilder';
import { InvoiceRepository } from '../repositories/invoiceRepository';
import { StudioRepository } from '../../studios/repositories/studioRepository';
import { Invoice } from '../models/invoiceModel';
import { Studio } from '../../studios/models/studioModel';

const inr = (n: number) => `Rs. ${n.toLocaleString('en-IN')}`;

const sanitize = (inv: Invoice) => ({
  id: inv.id,
  studioId: inv.studioId,
  eventId: inv.eventId,
  paymentId: inv.paymentId,
  invoiceNumber: inv.invoiceNumber,
  issuedAt: inv.issuedAt,
  placeOfSupply: inv.placeOfSupply,
  studioGstinSnapshot: inv.studioGstinSnapshot,
  subtotalInr: inv.subtotalInr,
  discountInr: inv.discountInr,
  taxableInr: inv.taxableInr,
  cgstInr: inv.cgstInr,
  sgstInr: inv.sgstInr,
  igstInr: inv.igstInr,
  totalInr: inv.totalInr,
  eventTitle: inv.event?.title ?? null,
  clientName: inv.event?.client?.name ?? null,
  createdAt: inv.createdAt,
  updatedAt: inv.updatedAt,
});

/** Renders a plain, print-friendly GST invoice. Synchronous/on-demand (not a
 *  queued job) — a single-page text layout is cheap enough to render inline,
 *  unlike thumbnailing or webhook processing which genuinely need a worker. */
function renderInvoicePdf(doc: PDFKit.PDFDocument, inv: Invoice, studio: Studio | null) {
  doc.fontSize(20).text(studio?.name ?? 'Studio', { continued: false });
  if (studio?.gstin) doc.fontSize(9).fillColor('#555').text(`GSTIN: ${studio.gstin}`);
  doc.moveDown(1.5);

  doc.fontSize(14).fillColor('#000').text('Tax Invoice', { align: 'right' });
  doc.fontSize(10).fillColor('#333');
  doc.text(`Invoice No: ${inv.invoiceNumber}`, { align: 'right' });
  doc.text(`Date: ${new Date(inv.issuedAt).toLocaleDateString('en-IN')}`, { align: 'right' });
  if (inv.placeOfSupply) doc.text(`Place of supply: ${inv.placeOfSupply}`, { align: 'right' });
  doc.moveDown(1);

  doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#ddd').stroke();
  doc.moveDown(0.8);

  doc.fontSize(11).fillColor('#000').text('Billed to');
  doc.fontSize(10).fillColor('#333').text(inv.event?.client?.name ?? 'Client');
  if (inv.event?.title) doc.fillColor('#666').text(inv.event.title);
  doc.moveDown(1.5);

  const rows: [string, string][] = [
    ['Subtotal', inr(inv.subtotalInr)],
    ['Discount', inr(inv.discountInr)],
    ['Taxable amount', inr(inv.taxableInr)],
    ['CGST', inr(inv.cgstInr)],
    ['SGST', inr(inv.sgstInr)],
    ['IGST', inr(inv.igstInr)],
  ];
  doc.fontSize(10).fillColor('#333');
  for (const [label, value] of rows) {
    doc.text(label, 50, doc.y, { continued: true, width: 400 });
    doc.text(value, { align: 'right' });
  }

  doc.moveDown(0.5);
  doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#ddd').stroke();
  doc.moveDown(0.5);

  doc.fontSize(13).fillColor('#000');
  doc.text('Total', 50, doc.y, { continued: true, width: 400 });
  doc.text(inr(inv.totalInr), { align: 'right' });

  doc.moveDown(2);
  doc.fontSize(8).fillColor('#999').text('Generated by FrameOS', 50, doc.y);
}

export class InvoiceService {
  static async list(studioId: string, query: BuiltQuery): Promise<ApiResponse> {
    try {
      const { rows, count } = await InvoiceRepository.findAndCountAllScoped(studioId, query);
      return buildListResponse(rows.map(sanitize), count, query.page);
    } catch (error) {
      return toErrorResponse(error, 'Failed to retrieve invoices');
    }
  }

  static async get(studioId: string, id: number): Promise<ApiResponse> {
    try {
      const inv = await InvoiceRepository.findByIdScoped(studioId, id);
      if (!inv) return buildError('Invoice not found', 404);
      return buildSuccess(sanitize(inv));
    } catch (error) {
      return toErrorResponse(error, 'Failed to retrieve invoice');
    }
  }

  /** GET /invoices/:id/pdf — streams the PDF directly; the router calls this
   *  instead of sendResponse() since a PDF response isn't a JSON ApiResponse. */
  static async streamPdf(studioId: string, id: number, res: Response): Promise<void> {
    const inv = await InvoiceRepository.findByIdScoped(studioId, id);
    if (!inv) {
      res.status(404).json({ statusCode: 404, success: false, message: 'Invoice not found' });
      return;
    }
    const studio = await StudioRepository.findById(studioId);

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `inline; filename="${inv.invoiceNumber}.pdf"`);

    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    doc.pipe(res);
    renderInvoicePdf(doc, inv, studio);
    doc.end();
  }
}
